include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code style
    prefer_single_quotes: true
    always_declare_return_types: true
    always_specify_types: true
    avoid_types_on_closure_parameters: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_constructors_first: true
    unnecessary_this: true

    # Error prevention
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_future: true
    avoid_empty_else: true
    avoid_shadowing_type_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    empty_statements: true
    no_duplicate_case_values: true
    null_closures: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    invalid_annotation_target: ignore
    always_specify_types: ignore
